Source/models/street_lists/views.py
# In this model, views.py files are the Flask Blueprint for this object.
# ie they describe what HTTP API endpoints are associated to objects of this class.
from flask import Blueprint, render_template, request, redirect, url_for
import Source.models.street_lists.street_list as Lists


__author__ = 'jslvtr'


street_list_blueprint = Blueprint('street_lists', __name__)


#
@street_list_blueprint.route('/', methods=['POST', 'GET'])
def get_streetlist():
    if request.method == 'POST':
        street = request.form['street'].strip()  # strip spaces from form inputs, so blanks end up as -- in URL route.
        # 20-9-17 however, regex validation on client side has already ensured no trailing spaces anyway.
        number = request.form['number'].strip()
        c1 = request.form['c1'].strip()
        c2 = request.form['c2'].strip()
        c3 = request.form['c3'].strip()
        # if any variables are "" or None, below list comprehension sets to '--' to attempt a RESTful URL string.
        number, c1, c2, c3 = ['--' if (x == "" or x is None) else x for x in [number, c1, c2, c3]]

        # below tried to serialize the mainlist StreetList object before to pass in the session,
        # but no time work this out, and probably not sensible approach anyway?
        # json_main = flask.jsonify(list=mainlist.serialize())
        # flask.session['mainlist'] = json_main
        # flask.session['sidelist'] = sidelist
        return redirect(url_for('.load_streetlist', street=street, number=number, c1=c1, c2=c2, c3=c3))
    else:
        return render_template('/404.jinja2')  # NB this seems to only trigger if already loaded POST data once


# iterates mainlist and sidelist objects in the template following Jose's Udemy tutorial item example
@street_list_blueprint.route('/<string:street>/<number>/<c1>/<c2>/<c3>', methods=['POST', 'GET'])
def load_streetlist(street, number, c1, c2, c3):
    mainlist = Lists.StreetList.get_mainlist(street, number)  # first StreetList object
    sidelist = Lists.StreetList.get_clist(c1, c2, c3)  # second StreetList object if any Box C streets needed
    return render_template('street_lists/street_list.jinja2', mainlist=mainlist, sidelist=sidelist, number=number,
                           street=street)

Source/models/street_reports/views.py
# In this model, views.py files are the Flask Blueprint for this object.
# ie they describe what HTTP API endpoints are associated to objects of this class.
from flask import Blueprint, render_template, request, redirect, url_for
import Source.models.street_reports.street_report as Report

__author__ = 'Will Croxford'

street_report_blueprint = Blueprint('street_reports', __name__)


# sideselection array has 0 to 3 length. Assume here for now max. 3 length.
# at moment if more than 3 streets selected, iterates over first 3.
@street_report_blueprint.route('/<string:number>', methods=['POST', 'GET'])
def get_streetreport(number):
    # gets my custom sequential ids of radio and any checkboxes selected, NB best to leave original Mongo IDs in place!
    mainselection = request.form['MainlistRadios']
    # control for nothing selected in lists already done with JS client side validation.
    sideselection = request.form.getlist('SidelistCheckboxes')

    # if we try sending sideselection array variable to the route, somehow this doesn't work, gives BSON error
    # after adding funny characters to field, like [//'.......//'] where .... is original ObjectId
    side = ["--", "--", "--"]
    for index in range(3):
        if len(sideselection) >= (index + 1):
            side[index] = sideselection[index]

    # should end up with length 3 array side, to pass to page, if no C street, sets to '--' for the URL.

    return redirect(url_for('.load_streetreport', mainselection=mainselection, side1=side[0], side2=side[1],
                            side3=side[2], number=number))


# 2nd method to put variables in URL here, call create_report in 2nd method not first!
@street_report_blueprint.route('/HouseNo:<string:number>/Street:<mainselection>/BoxC:<side1>/BoxC:<side2>/BoxC:<side3>',
                               methods=['POST', 'GET'])
def load_streetreport(mainselection, side1, side2, side3, number):
    # report is a StreetReport object, whose properties will be accessed in Jinja.
    report = Report.StreetReport.create_report(mainselection, side1, side2, side3, number)
    return render_template('street_reports/street_report.jinja2', report=report)

    # gave up trying to pass object in the session variable for now, could be bad approach also.
    # mainlist = flask.session['mainlist']
    # sidelist = flask.session['sidelist']

    # Do we need a try except clause for sideselection?

# maybe simplest try passing variables in url_for in Jinja template separated by ,
# which gets them all appended as queries to the URL, if we need to make the URL unique to the queries?

# check Jose chair application how to return exit function, (break is for loops only) and handle errors?

# Show previous streetlist and streetreport selections as lines on these pages, iterated from the collection,
# maybe need implement user login to do this, or can we do with just a session variable for now?

# And a trial method to insert new street on homepage? Message to tell people try and find your new street here?

# below works to generate UUID, but silly as need to pass other variables all in the URL also.
# This was my initial misunderstanding how dynamic URLs work.
# maybe do need session variable to store UUID somehow
# @street_report_blueprint.route('/', methods=['POST','GET'])
# def get_streetreport(reportid=uuid.uuid4().hex):
#     mainselection = request.form['MainlistRadios']
#     return redirect(url_for('.get_reportpage', reportid=reportid, mainselection=mainselection))
#
# @street_report_blueprint.route('/<string:reportid>/<string:mainselection>', methods=['POST', 'GET'])
# def get_reportpage(reportid, mainselection):
#
#     return render_template('street_reports/street_report.jinja2', reportid=reportid, mainselection=mainselection)

Source/templates/street_lists/street_list.jinja2
{% extends "base.jinja2" %}
{% block content %}

<script>

    // Client-side Javascript form validation, reduces load a little on server hopefully?
    // checks if either main or sidelist completely unchecked, then if so, shows alert and returns false,
    // stopping form submitting. Tx to https://stackoverflow.com/users/8299964/rajat-kumar-gupta for original snippet...

function validator(mainst, Cst) {
    if(document.querySelector('input[name="'+mainst+'"]:checked') == null ){
        alert("Please select a main street");
        return false;
    }

    // Only trigger C street validation if C streetlist is not empty..
    // first line below checks this

    else if (document.getElementsByName('SidelistCheckboxes').length != 0) {
    if (document.querySelector('input[name="'+Cst+'"]:checked') == null) {
        alert("Please select your C street(s), or if you don't have any C streets,"
        + "please click New Search and leave C fields all blank.");
        return false;
    }
 }}

  // extra clause to stop user selecting too many Box Cs, logic problem at moment still...
  // if (document.querySelectorAll('input[type="checkbox"]:checked').length) > 3)
  //  { alert("You have too many Box C streets chosen, 3 is the maximum"); return false;}


</script>



        <!-- div class="page-header" -->
            <h2 class="centre">Street List</h2>
        <!-- /div -->

{% if mainlist.list_length == 0 %}

<p>You have no possible results from your search: "{{ street }}"! <br/><br/>
Please check your spelling, <a href="/"  style="color:#00C300">click here</a> and try again.</p>

{% else %}

        <p>Please confirm one main street below, and if any Box C streets, confirm also in the lower table.<br/>
        Then click the report button at the bottom of this page.</p>
        {% if (number == "--") %}
            <p>You have not entered any property name or number on the previous page.</p>
        {% else %}
            <p>You have entered "{{ number }}" in the property name/number field on the previous page.</p>
        {% endif %}

<form class="form-horizontal" action = "{{ url_for('street_reports.get_streetreport', number=number) }}" method="post"
      onsubmit="return validator('MainlistRadios', 'SidelistCheckboxes')">
  <fieldset>
<!-- label name="maintest" id = "maintest"></label - can I pass mainlist object to blueprint in form? -->

<table class="table table-striped tablehead">
  <thead>
    <tr>
      <th  style="width:10%">&nbsp;</th>
      <th  style="width:40%">Street</th>
      <th  style="width:20%">Postal District</th>
      <th  style="width:30%">Number Range</th>
    </tr>
  </thead>
</table>

<div style="max-height: 160px; overflow-y: scroll; margin-top:0; padding-top:0;">
    <table class="table table-striped table-hover">
      <tbody>
            {% for index in range(mainlist.list_length) %}
                {% if mainlist.dummy[index] == False %}
                    <tr>
                {% else %}
                    <tr class = "red">
                {% endif %}
                   <td  style="width:10%"><input type="radio" name="MainlistRadios" id="{{ mainlist.id[index] }}" value="{{ mainlist.id[index] }}"></td>
                   <!-- label for="main{{ index }}" mainlist.id property -->
                   <td  style="width:40%">{{ mainlist.street[index] }}</td>
                   <td  style="width:20%">{{ mainlist.long_dist[index] }}</td>
                   <td  style="width:30%">{{ mainlist.numrange[index] }}</td>
                   <!--/label-->
                 </tr>
            {% endfor %}
      </tbody>
    </table>
</div>


{% if sidelist.list_length > 0 %}
    {% if sidelist.list_length > 1 %}
    <h3>Box C Streets</h3>
    {% else %}
    <h3>Box C Street (please still click it to confirm!)</h3>
    {% endif %}
    <table class="table table-striped table-hover tablehead">
      <thead>
        <tr>
          <th  style="width:10%">&nbsp;</th>
          <th  style="width:50%">Street</th>
          <th  style="width:40%">Postal District</th>
        </tr>
      </thead>
    </table>

<div style="max-height: 160px; overflow-y: scroll; margin-top:0; padding-top:0;">
    <table class="table table-striped table-hover">
      <tbody>
        {% for index2 in range(sidelist.list_length) %}
            {% if sidelist.dummy[index2] == False %}
                <tr>
            {% else %}
                <tr class = "red">
            {% endif %}
            <!-- put mongo id field as checkbox id value -->
           <td  style="width:10%"><input type="checkbox" name="SidelistCheckboxes" id="{{ sidelist.id[index2] }}" value="{{ sidelist.id[index2] }}"></td>
           <td  style="width:50%">{{ sidelist.street[index2] }}</td>
           <td  style="width:40%">{{ sidelist.long_dist[index2] }}</td>
         </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% else %}
<p>You have no Box C Street results in this search, just click the button below to show this search report.</p>
{% endif %}

<div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
            <button type="reset" class="btn btn-default">Clear</button>
            <button type="submit" class="btn btn-primary">Show Street Report</button>
        </div>
    </div>

</fieldset>
</form>

{% endif %}

{% endblock %}

<!-- testing, this comment is OK here, but if you put in wrong place inside Jinja tags, remember it
 will give you a very unhelpful 400 Bad Request Error! -->